services:
    
    acme_demo.admin.user:
        class: Acme\DemoBundle\Admin\UserAdmin
        arguments: [~, Acme\DemoBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User}

    acme_demo.admin.post:
        class: Acme\DemoBundle\Admin\PostAdmin
        arguments: [~, Acme\DemoBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Post}
